name: CI

on:
  push:
    branches:
      - main

jobs:
  buid:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run online scripts
      run: echo Hello World
    - name: Run a multi-line script
      run: |
        echo Hello World 1
        ls -la 
